# Generated by Django 5.0.7 on 2024-08-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(blank='true', max_length=500, null='true', verbose_name='Todo')),
            ],
        ),
    ]
